kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-smg-datascience-notebook
  namespace: profiling-openshift-test-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: thin
  volumeMode: Filesystem